name: snappy blog title
url: https://blog.snap-ci.com
pygments: true
paginate: 4
recent_posts: 4
safe: false
permalink: /blog/:year/:month/:day/:title/
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'README']
include: ['assets']
future: false
link:
  docs: https://docs.snap-ci.com/
  contact_us: https://snap-ci.com/contact-us/
