name: snappy blog title
url: http://blog.snap-ci.com
link:
  contact_us: https://snap-ci.com/contact-us
pygments: true
paginate: 5
recent_posts: 5
safe: false
permalink: /blog/:year/:month/:day/:title/
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'README']
include: ['assets']
