name: snappy blog title
url: http://blog.snap-ci.com
pygments: true
paginate: 3
recent_posts: 5
safe: false
permalink: /blog/:year/:month/:day/:title/
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'README']
include: ['assets']